[package]
name = "iyes_loopless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "fixedtimestep", "states" ]
fixedtimestep = [
    "bevy_core",
]
states = [
    "bevy_utils",
]

[dependencies]
bevy_ecs = "0.6.1"
bevy_core = { version = "0.6.0", optional = true }
bevy_utils = { version = "0.6.0", optional = true }

[dev-dependencies]
bevy = "0.6"
rand = "0.8.5"
